name: litellm

services:
  litellm:
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    #ports: !override
    #  - "127.0.0.1:4000:4000"

  db:
    volumes:
      - ../../data/litellm/postgres_data:/var/lib/postgresql/data
    #ports: !override
    #  - "127.0.0.1:5432:5432"

