
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true


credential_list:
  - credential_name: CmdCode-Anthropic
    credential_info:
      custom_llm_provider: Anthropic
    credential_values:
      api_base: "https://api.commandcode.ai/provider"
      api_key: os.environ/COMMANDCODE_API_KEY
  - credential_name: CmdCode-OpenAI
    credential_info:
      custom_llm_provider: OpenAI_Compatible
    credential_values:
      api_base: "https://api.commandcode.ai/provider/v1"
      api_key: os.environ/COMMANDCODE_API_KEY
  - credential_name: OpenCode-Anthropic
    credential_info:
      custom_llm_provider: Anthropic
    credential_values:
      api_base: "https://opencode.ai/zen/go"
      api_key: os.environ/OPENCODE_API_KEY
  - credential_name: OpenCode-OpenAI
    credential_info:
      custom_llm_provider: OpenAI_Compatible
    credential_values:
      api_base: "https://opencode.ai/zen/go/v1"
      api_key: os.environ/OPENCODE_API_KEY


mcp_servers:
  exa_search:
    alias: "exa_search"
    url: "https://mcp.exa.ai/mcp"
    transport: http
    auth_type: api_key
    auth_value: "os.environ/EXA_API_KEY"
  tavily_search:
    alias: "tavily_search"
    url: "https://mcp.tavily.com/mcp/?tavilyApiKey=${TAVILY_API_KEY}"
    transport: http
    variables:
      TAVILY_API_KEY:
        value: "os.environ/TAVILY_API_KEY"

model_list:

