services:
  picoclaw:
    container_name: ${COMPOSE_PROJECT_NAME}-gw
    image: localhost/picoclaw
    build:
      context: ./build/
      args:
        ALPINE_MIRROR: ${ALPINE_MIRROR:-}
        EXTRA_PKGS: ${EXTRA_PKGS:-}
    restart: unless-stopped
    hostname: pico-gw
    environment:
      - PICOCLAW_GATEWAY_HOST=0.0.0.0
      - TZ=Asia/Shanghai
    ports:
      - "${PICOCLAW_WEB_PORT}:18800"
      - "${PICOCLAW_GW_PORT}:18790"
    volumes:
      - home:/home/claw

volumes:
  home:
