services:
  hermes:
    container_name: hermes
    image: localhost/hermes:${HERMES_VER}
    build:
      context: ./build/
      args:
        HERMES_VER: ${HERMES_VER}
        DEBIAN_MIRROR: ${DEBIAN_MIRROR:-}
        EXTRA_PKGS: ${EXTRA_PKGS:-}
    restart: unless-stopped
    command: ["gateway", "run"]
    environment:
      HERMES_UID: ${HERMES_UID:-10000}
      HERMES_GID: ${HERMES_GID:-10000}
      HERMES_DASHBOARD: 1
      #HERMES_DASHBOARD_HOST: 0.0.0.0
      #HERMES_DASHBOARD_PORT: 9119
    env_file:
      - ./app.env
    ports:
      - "${HERMES_PORT:-127.0.0.1:9119}:9119"
    volumes:
      - data:/opt/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data:
